### ISSUE TITLE
numpy - gensim incompatibility

### ISSUE THREAD

**Issue by TandemElephant** [thibaudmartinez/node2vec#6]
Using `pip install https://github.com/thibaudmartinez/node2vec/releases/download/v0.2.0/node2vec-0.1.0-cp39-cp39-linux_x86_64.whl` on a `python:3.9-slim-bullseye` docker resulted in a successful installation (after running apt install build-essential for gcc, installed version (Debian 10.2.1-6) 10.2.1 20210110).

However, trying to import Node2Vec results in an error:
```
>>> from node2vec.model import Node2Vec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/node2vec/model.py", line 5, in <module>
    from gensim.models import Word2Vec
  File "/usr/local/lib/python3.9/site-packages/gensim/__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "/usr/local/lib/python3.9/site-packages/gensim/corpora/__init__.py", line 6, in <module>
    from .indexedcorpus import IndexedCorpus  # noqa:F401 must appear before the other classes
  File "/usr/local/lib/python3.9/site-packages/gensim/corpora/indexedcorpus.py", line 15, in <module>
    from gensim import interfaces, utils
  File "/usr/local/lib/python3.9/site-packages/gensim/interfaces.py", line 21, in <module>
    from gensim import utils, matutils
  File "/usr/local/lib/python3.9/site-packages/gensim/matutils.py", line 1104, in <module>
    from gensim._matutils import logsumexp, mean_absolute_difference, dirichlet_expectation
  File ".eggs/Cython-0.29.14-py2.7-linux-x86_64.egg/Cython/Includes/numpy/__init__.pxd", line 242, in init gensim._matutils
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Updating numpy to 1.22.4 fixed the issue.

**Comment by thibaudmartinez** [comment]
Thank you for raising this issue.

I updated numpy version to 1.22.4 to fix this problem: https://github.com/thibaudmartinez/node2vec/pull/7
